### ISSUE TITLE
ability to always check files in a directory

### ISSUE THREAD

**Issue by pcnate** [yokawasa/action-sqlcheck#16]
I have a build that creates an installation script from multiple input files that were generated. I do not seen an option to specify the folder. This folder is in my .gitignore. Anything like this exist?

**Comment by yokawasa** [comment]
@pcnate 

There is no option to specify the folder now, but i think it's a good option so I would like to add it as a new feature.

How do you like specifying the folder with the following `directories` parameter?  If you have multiple folder, maybe you can specify them with comma separator like `directories: resources/mydir1,resources/mydir2,resources/mydir3`

```yaml
jobs:
  sqlcheck:
    name: sqlcheck job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: yokawasa/action-sqlcheck@v1.2.1
      with:
        post-comment: true
        directories: resources/mydir
        token: ${{ secrets.GITHUB_TOKEN }}
```

By the way, if your folder is in your .gitignore, files under the folder will not be pushed into your GitHub repo, which mean the GitHub action cannot check them.

**Comment by pcnate** [comment]
Would it be better to use multiple lines in that case? I'm not great with yaml structure yet but something like this?

```yaml
jobs:
  sqlcheck:
    name: sqlcheck job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: yokawasa/action-sqlcheck@v1.2.1
      with:
        post-comment: true
        directories:
        - directory: resources/mydir1
        - directory: resources/mydir2
        token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by yokawasa** [comment]
@pcnate 
Thanks for the idea! Using multi-lines definitely look better but unfortunately array isn't supported type for action inputs

> Action inputs only supports string keys and string values at this time. This is because they translate to environment variables within the action’s execution run.
( ref: https://github.community/t/can-action-inputs-be-arrays/16457 )

But as suggested in page above, multi-line string can be possible. 
So how about this?

```
jobs:
  sqlcheck:
    name: sqlcheck job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: yokawasa/action-sqlcheck@v1.2.1
      with:
        post-comment: true
        directories: |
          resources/mydir1
          resources/mydir2
        token: ${{ secrets.GITHUB_TOKEN }}
```
By default, the action checks and identifies anti-patterns in SQL queries in any files in PR queries. But you can filter target files under specific directory(s) by specifying them using `directories` input parameter
