### ISSUE TITLE
PR comment is not posted

### ISSUE THREAD

**Issue by sh-jthorpe** [yokawasa/action-sqlcheck#26]
The action runs successfully, has output in the github action run, but a comment isn't posted to the PR.

```
      - uses: yokawasa/action-sqlcheck@v1.5.0
        with: 
          post-comment: true
          risk-level: 2
          token: ${{ secrets.GITHUB_TOKEN }}
          directories: |
            Sql
```

I don't see any obvious issues with the `post_pr_comment` method.

Maybe write it to $GITHUB_OUTPUT, so that users can post a comment themselves?

**Comment by yokawasa** [comment]
@sh-jthorpe I apologize for not responding for so long 🙏 
Can you try with `risk-level: 3` like this?  

```
      - uses: yokawasa/action-sqlcheck@v1.5.0
        with: 
          post-comment: true
          risk-level: 3
          token: ${{ secrets.GITHUB_TOKEN }}
          directories: |
            Sql
```
